AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - spec/**/*
    - public/**/*
    - tmp/**/*
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 120
